### ISSUE TITLE
[AVM Question/Feedback]: clone jsonls under the Azure organization

### ISSUE THREAD

**Issue by zioproto** [Azure/terraform-azurerm-avm-template#109]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Since we depend on jsonls:

https://github.com/Azure/terraform-azurerm-avm-template/blob/d9fa53d6ecc9647d518afd2f1698f47fa2c8dd2c/.github/actions/e2e-getexamples/action.yml#L19C1-L20C1

Should the https://github.com/matt-FFFFFF/jsonls  repo be moved under the Azure organization so that we can ensure proper governance of the code ?

thanks

**Comment by matt-FFFFFF** [comment]
Hi we can do, but this comes with its own issues.

Are there any other ways of easily getting a directory listing in a JSON array (with only dirs)?
