### ISSUE TITLE
terrafmt parameter correction in docs-check workflow

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-avm-template#37]
In this line here, I think it should be "$f" rather than "$$f" ?

https://github.com/Azure/terraform-azurerm-avm-template/blob/3eb7a2006253161c483dd52192c69e526dd4bd36/.github/actions/docs-check/action.yml#L30C93-L30C95

i.e.

```bash
        find . | egrep ".md|.tf" | grep -v README.md | sort | while read f; do terrafmt fmt $f; done
```

I'm getting "terrafmt: error reading path (9f): stat 9f: no such file or directory" otherwise, which looks the same as the workflows I see here.

**Comment by matt-FFFFFF** [comment]
thanks - this is a copy paste error from the makefile. - fixed in #39
