### ISSUE TITLE
Bug: Lint Checks Broken

### ISSUE THREAD

**Issue by jaredfholgate** [Azure/terraform-azurerm-avm-template#56]
This commit broke the linting checks for everyone: https://github.com/Azure/terraform-azurerm-avm-template/commit/4b539d38612a93d970e0bd1689020765a292f9ca

**Comment by jaredfholgate** [comment]
@lonegunmanb FYI

**Comment by lonegunmanb** [comment]
Hi @jaredfholgate thanks for reporting this issue to us, but I've checked the linting check on my own forked repo and it worked as expected. Would you please give me the error message you saw? Thanks.

**Comment by lonegunmanb** [comment]
Hi @jaredfholgate , I see where's the issue. You need override your [makefile](https://github.com/Azure/terraform-azurerm-avm-res-authorization-roleassignment/blob/main/Makefile) with the latest version from the [template repo](https://github.com/Azure/terraform-azurerm-avm-template/blob/main/Makefile)

**Comment by matt-FFFFFF** [comment]
Closing as fixed
