### ISSUE TITLE
terrafmt: not found

### ISSUE THREAD

**Issue by terrymandin** [Azure/terraform-azurerm-avm-template#84]
I am running into an issue with the ```docs-check``` action (see below).  This is preventing me from merging my code.  

Repository:  https://github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachinescaleset/actions

PR: https://github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachinescaleset/pull/11

Branch: https://github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachinescaleset/tree/vmss-avm-dev2

<img width="706" alt="image" src="https://github.com/Azure/terraform-azurerm-avm-template/assets/833055/b152fb70-5391-446b-9be5-3934b3968f9d">

**Comment by terrymandin** [comment]
Thanks for the quick response @matt-FFFFFF .  I did get the governance PR, but it is saying that I need approval from avm-admins and/or avm-core-team-technical.  I have to admit I'm not super deep on GitHub merging.  Am I able to merge this without one of the core team's approvals?

<img width="631" alt="image" src="https://github.com/Azure/terraform-azurerm-avm-template/assets/833055/e69758d5-3879-4cab-a3ab-c732ac68fd16">

**Comment by matt-FFFFFF** [comment]
@mbilalamjad please can you approve the grept PR?

**Comment by matt-FFFFFF** [comment]
I can't approve it as I created it (albeit through automation)

**Comment by mbilalamjad** [comment]
@matt-FFFFFF, @terrymandin I just approved the repo governance PR which should address this issue

**Comment by terrymandin** [comment]
Thanks for approving that.

I have merged this change into main:

<img width="517" alt="image" src="https://github.com/Azure/terraform-azurerm-avm-template/assets/833055/893e1d39-e03d-4925-b73c-60c2976915ec">

and pulled the changes into my branch via:

```git pull origin main```

But I am still seeing the same error:

<img width="707" alt="image" src="https://github.com/Azure/terraform-azurerm-avm-template/assets/833055/0921a7e9-4efe-4858-bc25-b9c050e2d161">

@matt-FFFFFF @mbilalamjad

**Comment by matt-FFFFFF** [comment]
Can you post a link to your branch and I'll take a look Monday

**Comment by terrymandin** [comment]
Sure, thanks @matt-FFFFFF .

Here is the branch:  https://github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachinescaleset/tree/vmss-avm-dev2

PR: https://github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachinescaleset/pull/11

Action:  https://github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachinescaleset/actions/runs/7762242621

**Comment by lonegunmanb** [comment]
@matt-FFFFFF I think this issue was caused by [this change](https://github.com/Azure/tfmod-scaffold/commit/4b93d0f2aabdc0f4450d07298219bc101e00ccb4), but this change itself is correct.

The real root cause is we don't have grept rules to exclude files that we don't want exist in a repo's github actions folder.

@terrymandin I think you can fix this issue by deleting [this file](https://github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachinescaleset/blob/vmss-avm-dev2/.github/workflows/docs-check.yml).

**Comment by terrymandin** [comment]
Thank you @lonegunmanb  and @matt-FFFFFF ,  deleting that file resolved the issue.
