### ISSUE TITLE
[AVM Module Issue]: problem in template datasource azurerm_resource_group parent

### ISSUE THREAD

**Issue by zioproto** [Azure/terraform-azurerm-avm-template#94]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Module specific issue

- [X] I confirm that this issue is about this AVM module and not about the resource itself, or how to use Terraform.

### Issue Type?

Bug

### Description

https://github.com/Azure/terraform-azurerm-avm-template/blob/84392a790fe7441247f013e9e251c84267ad3a90/main.tf#L2-L6

This code is failing for me in the GitHub action:
![Screenshot 2024-03-11 at 12 36 46](https://github.com/Azure/terraform-azurerm-avm-template/assets/789701/c9ab41a4-78e0-40ee-b119-2f5f57168540)

**Comment by matt-FFFFFF** [comment]
We are going to remove this functionality I think. It causes more problems than it solves

**Comment by segraef** [comment]
@matt-FFFFFF do we need more details for this?

**Comment by matt-FFFFFF** [comment]
This needs removing

https://github.com/Azure/terraform-azurerm-avm-template/blob/main/main.tf#L2-L7

Then the location is just passed in by value

**Comment by matt-FFFFFF** [comment]
Resolved
